### ISSUE TITLE
Anzeige Cookiebanner und DSGVO Disclaimer über Tracking

### ISSUE THREAD

**Issue by internaut** [IFAFMultiLA/adaptivelearnr#17]
- [x] Recherche bzgl. DSGVO Formulierungen
- [x] DSGVO Formulierung an DS-Beauftragte schicken (via Andre)
- [ ] Einwilligung ggf. überarbeiten
- [x] Einwilligung anzeigen

**Comment by internaut** [comment]
- siehe https://wiki.htw-berlin.de/confluence/display/htwberlinlehrestati/Datenschutz

**Comment by internaut** [comment]
- Anzeige des Modals implementiert via commit 5bf30b8
- Einwilligung muss ggf. noch überarbeitet werden (Feedback von DS-Beauftragter erwartet)
